<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="semantics" nsURI="http://www.xixum.org/semantics" nsPrefix="semantics">
  <eClassifiers xsi:type="ecore:EClass" name="INamable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDataComponent" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Property" abstract="true" eSuperTypes="#//IValueComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="IValueComponent" abstract="true" interface="true"
      eSuperTypes="#//INamable"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringProperty" eSuperTypes="#//Property #//IAggregated">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntProperty" eSuperTypes="#//Property #//IAtomic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatProperty" eSuperTypes="#//Property #//IAtomic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoolProperty" eSuperTypes="#//Property #//IAtomic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListProperty" eSuperTypes="#//Property #//IIterable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapProperty" eSuperTypes="#//Property #//IIterable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" upperBound="-1"
        eType="#//Pair" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pair">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//Property"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Property"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IIdentifiable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasID" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IAtomic" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAggregated" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IIterable" abstract="true" interface="true"
      eSuperTypes="#//IAggregated"/>
  <eClassifiers xsi:type="ecore:EClass" name="IContainable" abstract="true" interface="true"
      eSuperTypes="#//IAggregated"/>
  <eSubpackages name="artifact" nsURI="http://www.xixum.org/semantics/artifact" nsPrefix="artifact">
    <eClassifiers xsi:type="ecore:EClass" name="Artifact" eSuperTypes="#//INamable #//artifact/IPropertyable"/>
    <eClassifiers xsi:type="ecore:EClass" name="Document" eSuperTypes="#//artifact/Artifact">
      <eStructuralFeatures xsi:type="ecore:EReference" name="kg_reference" eType="#//knowledgegraph/Document"
          eOpposite="#//knowledgegraph/Document/context_ref"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextDocument" eSuperTypes="#//artifact/Document">
      <eStructuralFeatures xsi:type="ecore:EReference" name="blockElement" upperBound="-1"
          eType="#//artifact/ITextBodyEl" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SpreadSheet" eSuperTypes="#//artifact/Document">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sheet" upperBound="-1"
          eType="#//artifact/Sheet" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RichTextDocument" eSuperTypes="#//artifact/TextDocument"/>
    <eClassifiers xsi:type="ecore:EClass" name="Sheet" eSuperTypes="#//IDataComponent #//artifact/SpreatSheetComponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="table" upperBound="-1"
          eType="#//artifact/Table" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//IDataComponent #//artifact/SpreatSheetComponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="row" upperBound="-1"
          eType="#//artifact/Row" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Row" eSuperTypes="#//IDataComponent #//artifact/SpreatSheetComponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cell" upperBound="-1"
          eType="#//artifact/Cell" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Cell" eSuperTypes="#//IDataComponent #//artifact/SpreatSheetComponent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowSpan" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="colSpan" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="paragraph" upperBound="-1"
          eType="#//artifact/Paragraph" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Paragraph" eSuperTypes="#//artifact/ITextBodyEl #//IIdentifiable #//IDataComponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sentence" upperBound="-1"
          eType="#//artifact/Sentence" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Heading" eSuperTypes="#//artifact/ITextBodyEl #//IIdentifiable #//IDataComponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sentence" upperBound="-1"
          eType="#//artifact/Sentence" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ITextBodyEl" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="chunk" eType="#//knowledgegraph/Chunk"
          eOpposite="#//knowledgegraph/Chunk/context_ref"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Sentence" eSuperTypes="#//IDataComponent #//IContainable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="token" upperBound="-1"
          eType="#//artifact/Token" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Token" abstract="true" eSuperTypes="#//IDataComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="Word" eSuperTypes="#//artifact/Token">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="word" eType="#//dictionary/Word"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Number" eSuperTypes="#//artifact/Token">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//IAtomic"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedIdentity" eSuperTypes="#//artifact/Token">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IPropertyable" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
          eType="#//Property" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SpreatSheetComponent" abstract="true"
        interface="true" eSuperTypes="#//artifact/IPropertyable #//IDataComponent"/>
  </eSubpackages>
  <eSubpackages name="infrastructure" nsURI="http://www.xixum.org/semantics/infrastructure"
      nsPrefix="infrastructure">
    <eClassifiers xsi:type="ecore:EClass" name="Device" eSuperTypes="#//infrastructure/IInfrastructureEl #//infrastructure/ILocalLocation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subdir" upperBound="-1"
          eType="#//infrastructure/ISubDir" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PathEl" eSuperTypes="#//infrastructure/ISubDir">
      <eStructuralFeatures xsi:type="ecore:EReference" name="isubdir" upperBound="-1"
          eType="#//infrastructure/ISubDir" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artifact" upperBound="-1"
          eType="#//artifact/Artifact" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Domain" eSuperTypes="#//infrastructure/ILocation #//infrastructure/IWebLocation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subdir" upperBound="-1"
          eType="#//infrastructure/ISubDir" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ISubDir" abstract="true" interface="true"
        eSuperTypes="#//infrastructure/IInfrastructureEl"/>
    <eClassifiers xsi:type="ecore:EClass" name="IInfrastructureEl" abstract="true"
        interface="true" eSuperTypes="#//INamable"/>
    <eClassifiers xsi:type="ecore:EClass" name="Environment">
      <eStructuralFeatures xsi:type="ecore:EReference" name="location" upperBound="-1"
          eType="#//infrastructure/ILocation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ILocation" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ILocalLocation" abstract="true" interface="true"
        eSuperTypes="#//infrastructure/ILocation"/>
    <eClassifiers xsi:type="ecore:EClass" name="IWebLocation" abstract="true" interface="true"
        eSuperTypes="#//infrastructure/ILocation"/>
  </eSubpackages>
  <eSubpackages name="context" nsURI="http://www.xixum.org/semantics/context" nsPrefix="context">
    <eClassifiers xsi:type="ecore:EClass" name="ContextRoot" eSuperTypes="#//context/IContextEl">
      <eStructuralFeatures xsi:type="ecore:EReference" name="entity" upperBound="-1"
          eType="#//context/Entity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
          eType="#//context/Event" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="time" upperBound="-1"
          eType="#//context/Time" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relation" upperBound="-1"
          eType="#//context/Relation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="prototype" upperBound="-1"
          eType="#//context/Prototype" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Entity" abstract="true" eSuperTypes="#//context/IContextEl #//context/IRefferable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="state" upperBound="-1"
          eType="#//context/State" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="kg_entity" eType="#//knowledgegraph/Entity"
          eOpposite="#//knowledgegraph/Entity/context_ref"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="prototype" eType="#//context/Prototype"
          eOpposite="#//context/Prototype/entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//context/IContextEl">
      <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//context/Event"
          eOpposite="#//context/Event/previous"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//context/Event"
          eOpposite="#//context/Event/next"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="#//context/State"
          eOpposite="#//context/State/event"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="time" eType="#//context/Time"
          eOpposite="#//context/Time/event"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//context/IContextEl">
      <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//context/Event"
          eOpposite="#//context/Event/state"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Time" abstract="true" eSuperTypes="#//context/IContextEl #//context/IChronological">
      <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//context/Event"
          eOpposite="#//context/Event/time"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbsTime" eSuperTypes="#//context/Time"/>
    <eClassifiers xsi:type="ecore:EClass" name="RelativeTime" eSuperTypes="#//context/Time"/>
    <eClassifiers xsi:type="ecore:EClass" name="Relation" eSuperTypes="#//context/IContextEl">
      <eStructuralFeatures xsi:type="ecore:EReference" name="active_entity" eType="#//context/IRefferable"
          eOpposite="#//context/IRefferable/command"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="passive_entity" eType="#//context/IRefferable"
          eOpposite="#//context/IRefferable/operation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="kg_relation" eType="#//knowledgegraph/Relation"
          eOpposite="#//knowledgegraph/Relation/context_ref"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IContextEl" abstract="true" interface="true"
        eSuperTypes="#//INamable"/>
    <eClassifiers xsi:type="ecore:EClass" name="IChronological" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="after" eType="#//context/IChronological"
          eOpposite="#//context/IChronological/before"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="before" eType="#//context/IChronological"
          eOpposite="#//context/IChronological/after"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="synchronous" eType="#//context/IChronological"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PysicalE" eSuperTypes="#//context/Entity"/>
    <eClassifiers xsi:type="ecore:EClass" name="VirtualE" eSuperTypes="#//context/Entity"/>
    <eClassifiers xsi:type="ecore:EClass" name="Prototype" eSuperTypes="#//context/IRefferable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="abstract" eType="#//context/Prototype"
          eOpposite="#//context/Prototype/specification"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specification" upperBound="-1"
          eType="#//context/Prototype" eOpposite="#//context/Prototype/abstract"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//context/Entity"
          eOpposite="#//context/Entity/prototype"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IRefferable" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//context/Relation"
          eOpposite="#//context/Relation/passive_entity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="command" eType="#//context/Relation"
          eOpposite="#//context/Relation/active_entity"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="dictionary" nsURI="http://www.xixum.org/semantics/dictionary"
      nsPrefix="dictionary">
    <eClassifiers xsi:type="ecore:EClass" name="DictionaryRoot" eSuperTypes="#//dictionary/IDictionaryEl">
      <eStructuralFeatures xsi:type="ecore:EReference" name="word" upperBound="-1"
          eType="#//dictionary/Word" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="wordclass" upperBound="-1"
          eType="#//dictionary/WordClass" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Word" eSuperTypes="#//dictionary/IDictionaryEl">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ofType" upperBound="-1"
          eType="#//dictionary/WordClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="baseform" eType="#//dictionary/Word"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stem" upperBound="-1"
          eType="#//dictionary/Stem" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WordClass" eSuperTypes="#//dictionary/IDictionaryEl"/>
    <eClassifiers xsi:type="ecore:EClass" name="Stem" eSuperTypes="#//dictionary/IDictionaryEl"/>
    <eClassifiers xsi:type="ecore:EClass" name="IDictionaryEl" abstract="true" interface="true"
        eSuperTypes="#//INamable"/>
  </eSubpackages>
  <eSubpackages name="ruleset" nsURI="http://www.xixum.org/semantics/ruleset" nsPrefix="ruleset">
    <eClassifiers xsi:type="ecore:EClass" name="RuleRoot" eSuperTypes="#//ruleset/IRuleEl">
      <eStructuralFeatures xsi:type="ecore:EReference" name="token" upperBound="-1"
          eType="#//ruleset/Token" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="command" upperBound="-1"
          eType="#//ruleset/Command" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Token" eSuperTypes="#//ruleset/IRuleEl">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Command" eSuperTypes="#//ruleset/IRuleEl"/>
    <eClassifiers xsi:type="ecore:EClass" name="IRuleEl" abstract="true" interface="true"
        eSuperTypes="#//INamable"/>
  </eSubpackages>
  <eSubpackages name="knowledgegraph">
    <eClassifiers xsi:type="ecore:EClass" name="Document" eSuperTypes="#//knowledgegraph/INode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="chunk" upperBound="-1"
          eType="#//knowledgegraph/Chunk" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context_ref" eType="#//artifact/Document"
          eOpposite="#//artifact/Document/kg_reference"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Chunk" eSuperTypes="#//knowledgegraph/INode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="entity" upperBound="-1"
          eType="#//knowledgegraph/Entity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context_ref" eType="#//artifact/ITextBodyEl"
          eOpposite="#//artifact/ITextBodyEl/chunk"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//knowledgegraph/INode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="context_ref" eType="#//context/Entity"
          eOpposite="#//context/Entity/kg_entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="KGroot">
      <eStructuralFeatures xsi:type="ecore:EReference" name="document" upperBound="-1"
          eType="#//knowledgegraph/Document" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relation" upperBound="-1"
          eType="#//knowledgegraph/Relation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Relation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target_node" eType="#//knowledgegraph/INode"
          eOpposite="#//knowledgegraph/INode/in_relation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source_node" eType="#//knowledgegraph/INode"
          eOpposite="#//knowledgegraph/INode/out_relation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context_ref" eType="#//context/Relation"
          eOpposite="#//context/Relation/kg_relation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="INode" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="in_relation" eType="#//knowledgegraph/Relation"
          eOpposite="#//knowledgegraph/Relation/target_node"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="out_relation" eType="#//knowledgegraph/Relation"
          eOpposite="#//knowledgegraph/Relation/source_node"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
